name: GitHub Pages
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev
permissions:
    contents: write
defaults:
    run:
        working-directory: ./docs
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - run: npm ci
            - run: npm run playwright install
            - name: Build docs
              run: npm run build
            - name: no jekyll
              run: touch docs/dist/.nojekyll
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.6.4
              with:
                  folder: dist
                  single-commit: true