name: genai pull request
permissions:
    contents: read
    pull-requests: write
    models: read
on:
    pull_request:
    workflow_dispatch:
jobs:
    genai:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm ci
            - name: genai docs-editor
              run: npm run genai docs-editor -p github -prc -prr
